### ISSUE TITLE
Laravel Zero installation throws an error on the post-create-project-cmd

### ISSUE THREAD

**Issue by axelitus** [laravel-zero/laravel-zero#145]
This is my first laravel zero install and it is throwing an error:

```bash
$ laravel-zero new console command
# installation output ...
# ...
Generating optimized autoload files
> @php application app:rename
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to LaravelZero\Framework\Providers\GitVersion\GitVersionServiceProvider::LaravelZero\Framework\Providers\GitVersion\{closure}() must be an instance of Illuminate\Contracts\Console\Application, instance of LaravelZero\Framework\Application given, called in /home/axel/console-cmd/vendor/illuminate/container/Container.php on line 764 in /home/axel/console-cmd/vendor/laravel-zero/framework/src/Providers/GitVersion/GitVersionServiceProvider.php:32
Stack trace:
#0 /home/axel/console-cmd/vendor/illuminate/container/Container.php(764): LaravelZero\Framework\Providers\GitVersion\GitVersionServiceProvider->LaravelZero\Framework\Providers\GitVersion\{closure}(Object(LaravelZero\Framework\Application), Array)
#1 /home/axel/console-cmd/vendor/illuminate/container/Container.php(646): Illuminate\Container\Container->build(Object(Closure))
#2 /home/axel/console-cmd/vendor/illuminate/ in /home/axel/console-cmd/vendor/laravel-zero/framework/src/Providers/GitVersion/GitVersionServiceProvider.php on line 32
Script @php application app:rename handling the post-create-project-cmd event returned with error code 255
```

I also tried renaming the application manually:

```bash
~/command-cli $ php application app:rename command-cli
```

which yielded the same error.

I could track the error and it is because in the class `LaravelZero\Framework\Providers\GitVersion\GitVersionServiceProvider` the namespace import for the `Application` class is `Illuminate\Contracts\Console\Application`, but the object actually injected in the *register* method is in reallity of type `Illuminate\Foundation\Application`.

Changing the import statement fixes the issue and I can execute the commando without problems.

**Comment by nunomaduro** [comment]
@axelitus That problem should be now fixed. Sorry for the inconvenience! Do you mind of re-test?
