### ISSUE TITLE
mbstring not getting enabled in php-cli - unable to run Laravel Zero with mail functionality.

### ISSUE THREAD

**Issue by mathewp-maxamation** [laravel-zero/laravel-zero#336]
I added mail functionality to my Laravel Zero project and it works locally.

When trying to run on production I get the below error

```
[2021-03-03 10:12:19] production.ERROR: Call to undefined function mb_strcut() (View: ) (View: ) (View: ) {"exception":"[object] (ErrorException(code: 0): Call to undefined function mb_strcut() (View: ) (View: ) (View: ) at phar:///home/kallio/sendjob/kallio-send/vendor/league/commonmark/src/Util/RegexHelper.php:92)
[stacktrace]
#0 phar:///home/kallio/sendjob/kallio-send/vendor/illuminate/view/Engines/PhpEngine.php(60): Illuminate\\View\\Engines\\CompilerEngine->handleViewException(Object(ErrorException), 0)
#1 phar:///home/kallio/sendjob/kallio-send/vendor/illuminate/view/Engines/CompilerEngine.php(61): Illuminate\\View\\Engines\\PhpEngine->evaluatePath('/home/kallio/se...', Array)
#2 phar:///home/kallio/sendjob/kallio-send/vendor/illuminate/view/View.php(139): Illuminate\\View\\Engines\\CompilerEngine->get('phar:///home/ka...', Array)
#3 phar:///home/kallio/sendjob/kallio-send/vendor/illuminate/view/View.php(122): Illuminate\\View\\View->getContents()
#4 phar:///home/kallio/sendjob/kallio-send/vendor/illuminate/view/View.php(91): Illuminate\\View\\View->renderContents()
#5 phar:///home/kallio/sendjob/kallio-send/vendor/illuminate/mail/Markdown.php(64): Illuminate\\View\\View->render()
#6 phar:///home/kallio/sendjob/kallio-send/vendor/illuminate/mail/Mailable.php(304): Illuminate\\Mail\\Markdown->render('emails.rejects', Array)
#7 phar:///home/kallio/sendjob/kallio-send/vendor/illuminate/mail/Mailable.php(274): Illuminate\\Mail\\Mailable->buildMarkdownView()
#8 phar:///home/kallio/sendjob/kallio-send/vendor/illuminate/mail/Mailable.php(180): Illuminate\\Mail\\Mailable->buildView()
#9 phar:///home/kallio/sendjob/kallio-send/vendor/illuminate/support/Traits/Localizable.php(19): Illuminate\\Mail\\Mailable->Illuminate\\Mail\\{closure}()
#10 phar:///home/kallio/sendjob/kallio-send/vendor/illuminate/mail/Mailable.php(187): Illuminate\\Mail\\Mailable->withLocale(NULL, Object(Closure))
#11 phar:///home/kallio/sendjob/kallio-send/vendor/illuminate/mail/Mailer.php(304): Illuminate\\Mail\\Mailable->send(Object(Illuminate\\Mail\\Mailer))
#12 phar:///home/kallio/sendjob/kallio-send/vendor/illuminate/mail/Mailer.php(258): Illuminate\\Mail\\Mailer->sendMailable(Object(App\\Mail\\RecordsRejected))
#13 phar:///home/kallio/sendjob/kallio-send/vendor/illuminate/mail/PendingMail.php(121): Illuminate\\Mail\\Mailer->send(Object(App\\Mail\\RecordsRejected))
#14 phar:///home/kallio/sendjob/kallio-send/app/PSS/Engine.php(98): Illuminate\\Mail\\PendingMail->send(Object(App\\Mail\\RecordsRejected))
#15 phar:///home/kallio/sendjob/kallio-send/app/PSS/Engine.php(89): App\\PSS\\Engine->sendRejectEmailIfAnyRecordsWereRejected()
#16 phar:///home/kallio/sendjob/kallio-send/vendor/nunomaduro/laravel-console-task/src/LaravelConsoleTaskServiceProvider.php(49): App\\PSS\\Engine->App\\PSS\\{closure}()
#17 phar:///home/kallio/sendjob/kallio-send/vendor/illuminate/macroable/Traits/Macroable.php(114): App\\Commands\\SendOpt->NunoMaduro\\LaravelConsoleTask\\{closure}('Sending reject ...', Object(Closure))
#18 phar:///home/kallio/sendjob/kallio-send/vendor/laravel-zero/framework/src/Commands/Command.php(56): Illuminate\\Console\\Command->__call('task', Array)
#19 phar:///home/kallio/sendjob/kallio-send/app/Commands/SendOpt.php(52): LaravelZero\\Framework\\Commands\\Command->task('Sending reject ...', Object(Closure))
#20 phar:///home/kallio/sendjob/kallio-send/app/PSS/Engine.php(330): App\\Commands\\SendOpt->runTask('Sending reject ...', Object(Closure))
#21 phar:///home/kallio/sendjob/kallio-send/app/PSS/Engine.php(90): App\\PSS\\Engine->showTaskIfVerboseMode('Sending reject ...', Object(Closure))
#22 phar:///home/kallio/sendjob/kallio-send/app/Commands/SendOpt.php(69): App\\PSS\\Engine->sendOpts(Object(App\\Commands\\SendOpt))
#23 phar:///home/kallio/sendjob/kallio-send/vendor/illuminate/container/BoundMethod.php(36): App\\Commands\\SendOpt->handle(Object(App\\PSS\\Navitaire\\v1_0\\Navitaire_V1_0))
#24 phar:///home/kallio/sendjob/kallio-send/vendor/illuminate/container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#25 phar:///home/kallio/sendjob/kallio-send/vendor/illuminate/container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#26 phar:///home/kallio/sendjob/kallio-send/vendor/illuminate/container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(LaravelZero\\Framework\\Application), Array, Object(Closure))
#27 phar:///home/kallio/sendjob/kallio-send/vendor/illuminate/container/Container.php(610): Illuminate\\Container\\BoundMethod::call(Object(LaravelZero\\Framework\\Application), Array, Array, NULL)
#28 phar:///home/kallio/sendjob/kallio-send/vendor/illuminate/console/Command.php(136): Illuminate\\Container\\Container->call(Array)
#29 phar:///home/kallio/sendjob/kallio-send/vendor/symfony/console/Command/Command.php(256): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#30 phar:///home/kallio/sendjob/kallio-send/vendor/illuminate/console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#31 phar:///home/kallio/sendjob/kallio-send/vendor/symfony/console/Application.php(971): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#32 phar:///home/kallio/sendjob/kallio-send/vendor/symfony/console/Application.php(290): Symfony\\Component\\Console\\Application->doRunCommand(Object(App\\Commands\\SendOpt), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#33 phar:///home/kallio/sendjob/kallio-send/vendor/symfony/console/Application.php(166): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#34 phar:///home/kallio/sendjob/kallio-send/vendor/illuminate/console/Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#35 phar:///home/kallio/sendjob/kallio-send/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#36 phar:///home/kallio/sendjob/kallio-send/vendor/laravel-zero/framework/src/Kernel.php(91): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#37 phar:///home/kallio/sendjob/kallio-send/kallio-send(36): LaravelZero\\Framework\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#38 /home/kallio/sendjob/kallio-send(14): require('phar:///home/ka...')
#39 {main}
```

I installed mbstring extention using:

```sudo apt install php7.3-mbstring```

It still didn't work. So I ran ```php --ini``` and found the loaded INI file

```
ubuntu@0b-prod:/home$ php --ini
Configuration File (php.ini) Path: /etc/php/7.3/cli
Loaded Configuration File:         /etc/php/7.3/cli/php.ini
Scan for additional .ini files in: /etc/php/7.3/cli/conf.d
Additional .ini files parsed:      /etc/php/7.3/cli/conf.d/10-opcache.ini,
/etc/php/7.3/cli/conf.d/10-pdo.ini,
/etc/php/7.3/cli/conf.d/20-calendar.ini,
/etc/php/7.3/cli/conf.d/20-ctype.ini,
/etc/php/7.3/cli/conf.d/20-curl.ini,
/etc/php/7.3/cli/conf.d/20-exif.ini,
/etc/php/7.3/cli/conf.d/20-fileinfo.ini,
/etc/php/7.3/cli/conf.d/20-ftp.ini,
/etc/php/7.3/cli/conf.d/20-gettext.ini,
/etc/php/7.3/cli/conf.d/20-iconv.ini,
/etc/php/7.3/cli/conf.d/20-json.ini,
/etc/php/7.3/cli/conf.d/20-mbstring.ini,
/etc/php/7.3/cli/conf.d/20-phar.ini,
/etc/php/7.3/cli/conf.d/20-posix.ini,
/etc/php/7.3/cli/conf.d/20-readline.ini,
/etc/php/7.3/cli/conf.d/20-shmop.ini,
/etc/php/7.3/cli/conf.d/20-sockets.ini,
/etc/php/7.3/cli/conf.d/20-sysvmsg.ini,
/etc/php/7.3/cli/conf.d/20-sysvsem.ini,
/etc/php/7.3/cli/conf.d/20-sysvshm.ini,
/etc/php/7.3/cli/conf.d/20-tokenizer.ini
```

Then I edited /etc/php/7.3/cli/php.ini and uncommented ```extension=mbstring``` and tried again. It still didn't work.

Since this is a CLI application - I believe I've updated the correct file. 

Any help is appreciated.

**Comment by mathewp-maxamation** [comment]
My bad. I was working on two different servers. INstalled in one, tested in another.

**Comment by owenvoke** [comment]
No worries @mathewp-maxamation, glad you resolved the issue. 👍🏻
