### ISSUE TITLE
app:build (standalone) : No such file or directory when moving/renaming generated phar

### ISSUE THREAD

**Issue by alexc-wormhole** [laravel-zero/laravel-zero#350]
I have a Zero app dockerised and invoke it normally like this:

```
docker run --rm -i example/my-cli:latest app:build
```

Composer

```
    "require": {
        "php": "^7.3|^8.0",
        "laravel-zero/framework": "^8.8",
        "evilfreelancer/routeros-api-php": "^1.3",
        "illuminate/support": "^8.18",
        "padraic/phar-updater": "^1.0.6",
        "salmanzafar/laravel-mqtt": "^2.0"
    },
    "require-dev": {
        "mockery/mockery": "^1.4.2",
        "pestphp/pest": "^0.3"
    },
```

box,json

```
{
    "chmod": "0755",
    "directories": [
        "app",
        "bootstrap",
        "config",
        "vendor"
    ],
    "files": [
        "composer.json"
    ],
    "exclude-composer-files": false,
    "compression": "GZ",
    "compactors": [
        "KevinGH\\Box\\Compactor\\Php",
        "KevinGH\\Box\\Compactor\\Json"
    ]
}

```

Output:

```
Build version? [unreleased]:
 > 1.0

   1. Moving application to production mode: loading...
   1. Moving application to production mode: ✔

  1/25 [=🍺--------------------------]   4%
 25/25 [============================] 100%   2. Compile into a single file: loading...
   2. Compile into a single file: ✔


   ErrorException 

  rename(/example/cli/my-cli.phar,/example/my-cli/builds/my-cli): No such file or directory

  at my-cli/vendor/illuminate/filesystem/Filesystem.php:305
    301▕      * @return bool
    302▕      */
    303▕     public function move($path, $target)
    304▕     {
  ➜ 305▕         return rename($path, $target);
    306▕     }
    307▕ 
    308▕     /**
    309▕      * Copy a file to a new location.

      +20 vendor frames 
  21 my-cli/my-cli:37
      LaravelZero\Framework\Kernel::handle()

```

**Comment by owenvoke** [comment]
Please could you try running in verbose mode with `my-cli app:build -v`?

That should dump the output of the Box release and show up any underlying issues. 👍🏻

**Comment by alexc-wormhole** [comment]
Sure - thanks for the quick response.

```
Build version? [unreleased]:
 > 1.0

   1. Moving application to production mode: loading...
   1. Moving application to production mode: ✔

    ____
   / __ )____  _  __
  / __  / __ \| |/_/
 / /_/ / /_/ />  <
/_____/\____/_/|_|


Box version 3.13.0@275b091 2021-05-15 19:13:46 UTC



 // Loading the configuration file                                              

 // "/example/my-cli/box.json".                             



PHP Fatal error:  Uncaught Error: Call to undefined function ctype_alpha() in phar:///example/my-cli/vendor/laravel-zero/framework/bin/box/vendor/webmozart/path-util/src/Path.php:193
Stack trace:
#0 phar:///example/my-cli/vendor/laravel-zero/framework/bin/box/vendor/webmozart/path-util/src/Path.php(213): _HumbugBox113887eee2b6\Webmozart\PathUtil\Path::isAbsolute()
#1 phar:///example/my-cli/vendor/laravel-zero/framework/bin/box/src/FileSystem/FileSystem.php(81): _HumbugBox113887eee2b6\Webmozart\PathUtil\Path::makeAbsolute()
#2 phar:///example/my-cli/vendor/laravel-zero/framework/bin/box/src/FileSystem/file_system.php(108): _HumbugBox113887eee2b6\KevinGH\Box\FileSystem\FileSystem->makeAbsolute()
#3 phar:///example/my-cli/vendor/laravel-zero/framework/bin/box/src/Configuration/Configuration.php(817): _HumbugBox113887eee2b6\KevinGH\Box\FileSystem\make_path_absolute()
#4 phar:///example/my-cli/vendor/laravel-zero/ in phar:///example/my-cli/vendor/laravel-zero/framework/bin/box/vendor/webmozart/path-util/src/Path.php on line 193


   2. Compile into a single file: loading...
   2. Compile into a single file: ✔


   ErrorException 

  rename(/example/my-cli/my-cli.phar,/example/my-cli/builds/my-cli): No such file or directory

  at my-cli/vendor/illuminate/filesystem/Filesystem.php:305
    301▕      * @return bool
    302▕      */
    303▕     public function move($path, $target)
    304▕     {
  ➜ 305▕         return rename($path, $target);
    306▕     }
    307▕ 
    308▕     /**
    309▕      * Copy a file to a new location.

  1   my-cli/vendor/illuminate/filesystem/Filesystem.php:305
      rename()

  2   my-cli/vendor/illuminate/support/Facades/Facade.php:261
      Illuminate\Filesystem\Filesystem::move()

  3   my-cli/vendor/laravel-zero/framework/src/Commands/BuildCommand.php:143
      Illuminate\Support\Facades\Facade::__callStatic()

  4   my-cli/vendor/laravel-zero/framework/src/Commands/BuildCommand.php:93
      LaravelZero\Framework\Commands\BuildCommand::compile()

  5   my-cli/vendor/laravel-zero/framework/src/Commands/BuildCommand.php:71
      LaravelZero\Framework\Commands\BuildCommand::build()

  6   my-cli/vendor/illuminate/container/BoundMethod.php:36
      LaravelZero\Framework\Commands\BuildCommand::handle()

  7   my-cli/vendor/illuminate/container/Util.php:40
      Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()

  8   my-cli/vendor/illuminate/container/BoundMethod.php:93
      Illuminate\Container\Util::unwrapIfClosure()

  9   my-cli/vendor/illuminate/container/BoundMethod.php:37
      Illuminate\Container\BoundMethod::callBoundMethod()

  10  my-cli/vendor/illuminate/container/Container.php:651
      Illuminate\Container\BoundMethod::call()

  11  my-cli/vendor/illuminate/console/Command.php:136
      Illuminate\Container\Container::call()

  12  my-cli/vendor/symfony/console/Command/Command.php:299
      Illuminate\Console\Command::execute()

  13  my-cli/vendor/illuminate/console/Command.php:121
      Symfony\Component\Console\Command\Command::run()

  14  my-cli/vendor/laravel-zero/framework/src/Commands/BuildCommand.php:79
      Illuminate\Console\Command::run()

  15  my-cli/vendor/symfony/console/Application.php:978
      LaravelZero\Framework\Commands\BuildCommand::run()

  16  my-cli/vendor/symfony/console/Application.php:295
      Symfony\Component\Console\Application::doRunCommand()

  17  my-cli/vendor/symfony/console/Application.php:167
      Symfony\Component\Console\Application::doRun()

  18  my-cli/vendor/illuminate/console/Application.php:92
      Symfony\Component\Console\Application::run()

  19  my-cli/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Console/Kernel.php:129
      Illuminate\Console\Application::run()

  20  my-cli/vendor/laravel-zero/framework/src/Kernel.php:91
      Illuminate\Foundation\Console\Kernel::handle()

  21  -mikrotik-cli/mikrotik-cli:37
      LaravelZero\Framework\Kernel::handle()

```

**Comment by alexc-wormhole** [comment]
Ahaa! Adding the `php-ctype` extension on Alpine seems to have fixed it! Thanks again.

**Comment by alexc-wormhole** [comment]
For anyone curious, here's the Dockerfile. PECL Mosquitto extension isn't up to v8 yet so it has to stay at 7.4.

Build command:

```
docker build -t example/my-cli:latest path/to/dir/with/dockerfile --no-cache
```

Which runs this:

```
FROM alpine

ADD https://packages.whatwedo.ch/php-alpine.rsa.pub /etc/apk/keys/php-alpine.rsa.pub

RUN apk --update-cache add git zip unzip wget curl ca-certificates composer gcc make g++ zlib-dev mosquitto-libs mosquitto-dev && \
    echo "https://packages.whatwedo.ch/php-alpine/v3.12/php-7.4" >> /etc/apk/repositories

RUN apk add --update-cache \
    php \
    php-bz2 \
    php-bcmath \
    php-common \
    php-ctype \
    php-curl \
    php7-dev \
    php-dom \
    php-ftp \
    php-fileinfo \
    php-iconv \
    php-intl \
    php-json \
    php-mbstring \
    php-mongodb \
    php-openssl \
    php-phar \
    php-redis \
    php-soap \
    php-sockets \
    php-sqlite3 \
    php-tokenizer \
    php-xml \
    php-xmlreader \
    php-xmlwriter \
    php-zip

RUN wget -nv http://pear.php.net/go-pear.phar \
    && php go-pear.phar \
    && pecl channel-update pecl.php.net

RUN pecl install Mosquitto-alpha
RUN echo "extension=mosquitto.so" > /etc/php7/conf.d/10-mosquitto.ini

RUN mkdir /example

WORKDIR /example

RUN git clone https://bitbucket.org/vendor-name/some-repo.git \
  && cd some-repo \
  && composer install --ignore-platform-reqs --no-progress \
  && composer update --ignore-platform-reqs --no-progress

RUN some-repo/my-cli app:build -v --build-version=1.0
RUN chmod +x some-repo/builds/my-cli

ENTRYPOINT ["some-repo/builds/my-cli"]
```

Check it's built OK:

```
docker image ls

REPOSITORY      TAG         IMAGE ID          CREATED          SIZE
example/my-cli      latest       af91de44506e   8 minutes ago    162MB

```

Then to run:

```
docker run --rm -i example/my-cli:latest app:build -v
docker run --rm -i example/my-cli:latest some:command -v
```

**Comment by owenvoke** [comment]
Glad you managed to get it sorted. 👍🏻
