### ISSUE TITLE
Cannot build since PHP 8.1

### ISSUE THREAD

**Issue by loranger** [laravel-zero/laravel-zero#367]
Hello, I've got a simple app I cannot build anymore since homebrew upgraded PHP to latest 8.1 version.

It seems it's a box issue, but I really don't know what I can do in order to fix it

```shell
❯ ./nas app:build


                Building process


 Build version? [unreleased]:
 >

   1. Moving application to production mode: ✔
   2. Compile into a single file: ✔


   ErrorException

  rename(/Users/loranger/Developer/projects/nas-cli/nas.phar,/Users/loranger/Developer/projects/nas-cli/builds/nas): No such file or directory

  at vendor/illuminate/filesystem/Filesystem.php:305
    301▕      * @return bool
    302▕      */
    303▕     public function move($path, $target)
    304▕     {
  ➜ 305▕         return rename($path, $target);
    306▕     }
    307▕
    308▕     /**
    309▕      * Copy a file to a new location.

      +20 vendor frames
  21  nas:37
      LaravelZero\Framework\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

<details>
<summary><code>composer.json</code></summary>

```json
    "require": {
        "php": "^7.3|^8.0",
        "laravel-zero/framework": "^8.8",
        "titasgailius/terminal": "^1"
    },
    "require-dev": {
        "mockery/mockery": "^1.4.3",
        "pestphp/pest": "^1.3"
    },
```
</details>

<details>
<summary><code>box.json</code></summary>

```json
{
    "chmod": "0755",
    "directories": [
        "app",
        "bootstrap",
        "config",
        "vendor"
    ],
    "files": [
        "composer.json"
    ],
    "exclude-composer-files": false,
    "compression": "GZ",
    "compactors": [
        "KevinGH\\Box\\Compactor\\Php",
        "KevinGH\\Box\\Compactor\\Json"
    ]
}
```
</details>

<details>
<summary><code>./nas app:build -v</code></summary>

```shell
❯ ./nas app:build -v


                Building process


 Build version? [unreleased]:
 >

   1. Moving application to production mode: ✔

PHP Deprecated:  Return type of HumbugBox3130\KevinGH\RequirementChecker\RequirementCollection::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/bin/box/.box/src/RequirementCollection.php on line 12
PHP Deprecated:  Return type of HumbugBox3130\KevinGH\RequirementChecker\RequirementCollection::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/bin/box/.box/src/RequirementCollection.php on line 16


Deprecated: Return type of HumbugBox3130\KevinGH\RequirementChecker\RequirementCollection::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/bin/box/.box/src/RequirementCollection.php on line 12

Deprecated: Return type of HumbugBox3130\KevinGH\RequirementChecker\RequirementCollection::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/bin/box/.box/src/RequirementCollection.php on line 16


Deprecated: Return type of _HumbugBox113887eee2b6\iter\rewindable\_RewindableGenerator::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/bin/box/vendor/nikic/iter/src/iter.rewindable.php on line 162

Deprecated: Return type of _HumbugBox113887eee2b6\iter\rewindable\_RewindableGenerator::next() should either be compatible with Iterator::next(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/bin/box/vendor/nikic/iter/src/iter.rewindable.php on line 141

Deprecated: Return type of _HumbugBox113887eee2b6\iter\rewindable\_RewindableGenerator::key() should either be compatible with Iterator::key(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/bin/box/vendor/nikic/iter/src/iter.rewindable.php on line 155

Deprecated: Return type of _HumbugBox113887eee2b6\iter\rewindable\_RewindableGenerator::valid() should either be compatible with Iterator::valid(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/bin/box/vendor/nikic/iter/src/iter.rewindable.php on line 148

Deprecated: Return type of _HumbugBox113887eee2b6\iter\rewindable\_RewindableGenerator::rewind() should either be compatible with Iterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/bin/box/vendor/nikic/iter/src/iter.rewindable.php on line 136

PHP Deprecated:  Return type of _HumbugBox113887eee2b6\iter\rewindable\_RewindableGenerator::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/bin/box/vendor/nikic/iter/src/iter.rewindable.php on line 162
PHP Deprecated:  Return type of _HumbugBox113887eee2b6\iter\rewindable\_RewindableGenerator::next() should either be compatible with Iterator::next(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/bin/box/vendor/nikic/iter/src/iter.rewindable.php on line 141
PHP Deprecated:  Return type of _HumbugBox113887eee2b6\iter\rewindable\_RewindableGenerator::key() should either be compatible with Iterator::key(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/bin/box/vendor/nikic/iter/src/iter.rewindable.php on line 155
PHP Deprecated:  Return type of _HumbugBox113887eee2b6\iter\rewindable\_RewindableGenerator::valid() should either be compatible with Iterator::valid(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/bin/box/vendor/nikic/iter/src/iter.rewindable.php on line 148
PHP Deprecated:  Return type of _HumbugBox113887eee2b6\iter\rewindable\_RewindableGenerator::rewind() should either be compatible with Iterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/bin/box/vendor/nikic/iter/src/iter.rewindable.php on line 136


Deprecated: Return type of _HumbugBox113887eee2b6\Symfony\Component\Finder\Finder::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/bin/box/vendor/symfony/finder/Finder.php on line 220

Deprecated: Return type of _HumbugBox113887eee2b6\Symfony\Component\Finder\Finder::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/bin/box/vendor/symfony/finder/Finder.php on line 271

PHP Deprecated:  Return type of _HumbugBox113887eee2b6\Symfony\Component\Finder\Finder::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/bin/box/vendor/symfony/finder/Finder.php on line 220
PHP Deprecated:  Return type of _HumbugBox113887eee2b6\Symfony\Component\Finder\Finder::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/bin/box/vendor/symfony/finder/Finder.php on line 271


Fatal error: During inheritance of IteratorAggregate: Uncaught ErrorException: Return type of _HumbugBox113887eee2b6\Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/bin/box/vendor/symfony/console/Helper/HelperSet.php:44
Stack trace:
#0 phar:///Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/bin/box/vendor/symfony/console/Helper/HelperSet.php(7): _HumbugBox113887eee2b6\KevinGH\Box\{closure}(8192, 'Return type of ...', 'phar:///Users/l...', 44)
#1 phar:///Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/bin/box/.box/vendor/composer/ClassLoader.php(478): include('phar:///Users/l...')
#2 phar:///Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/bin/box/.box/vendor/composer/ClassLoader.php(346): Composer\Autoload\includeFile('phar:///Users/l...')
#3 phar:///Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/bin/box/vendor/symfony/console/Application.php(682): Composer\Autoload\ClassLoader->loadClass('_HumbugBox11388...')
#4 phar:///Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/bin/box/src/Console/Application.php(56): _HumbugBox113887eee2b6\Symfony\Component\Console\Application->getDefaultHelperSet()
#5 phar:///Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/bin/box/vendor/symfony/console/Application.php(204): _HumbugBox113887eee2b6\KevinGH\Box\Console\Application->getDefaultHelperSet()
#6 phar:///Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/bin/box/vendor/symfony/console/Command/Command.php(55): _HumbugBox113887eee2b6\Symfony\Component\Console\Application->getHelperSet()
#7 phar:///Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/bin/box/vendor/symfony/console/Application.php(283): _HumbugBox113887eee2b6\Symfony\Component\Console\Command\Command->setApplication(Object(_HumbugBox113887eee2b6\KevinGH\Box\Console\Application))
#8 phar:///Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/bin/box/vendor/symfony/console/Application.php(787): _HumbugBox113887eee2b6\Symfony\Component\Console\Application->add(Object(_HumbugBox113887eee2b6\Symfony\Component\Console\Command\HelpCommand))
#9 phar:///Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/bin/box/vendor/symfony/console/Application.php(362): _HumbugBox113887eee2b6\Symfony\Component\Console\Application->init()
#10 phar:///Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/bin/box/vendor/symfony/console/Application.php(163): _HumbugBox113887eee2b6\Symfony\Component\Console\Application->find('compile')
#11 phar:///Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/bin/box/vendor/symfony/console/Application.php(101): _HumbugBox113887eee2b6\Symfony\Component\Console\Application->doRun(Object(_HumbugBox113887eee2b6\Symfony\Component\Console\Input\ArgvInput), Object(_HumbugBox113887eee2b6\Symfony\Component\Console\Output\ConsoleOutput))
#12 phar:///Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/bin/box/bin/box(41): _HumbugBox113887eee2b6\Symfony\Component\Console\Application->run()
#13 /Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/bin/box(18): require('phar:///Users/l...')
#14 {main} in phar:///Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/bin/box/vendor/symfony/console/Helper/HelperSet.php on line 7

PHP Fatal error:  During inheritance of IteratorAggregate: Uncaught ErrorException: Return type of _HumbugBox113887eee2b6\Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/bin/box/vendor/symfony/console/Helper/HelperSet.php:44
Stack trace:
#0 phar:///Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/bin/box/vendor/symfony/console/Helper/HelperSet.php(7): _HumbugBox113887eee2b6\KevinGH\Box\{closure}(8192, 'Return type of ...', 'phar:///Users/l...', 44)
#1 phar:///Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/bin/box/.box/vendor/composer/ClassLoader.php(478): include('phar:///Users/l...')
#2 phar:///Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/bin/box/.box/vendor/composer/ClassLoader.php(346): Composer\Autoload\includeFile('phar:///Users/l...')
#3 phar:///Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/bin/box/vendor/symfony/console/Application.php(682): Composer\Autoload\ClassLoader->loadClass('_HumbugBox11388...')
#4 phar:///Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/bin/box/src/Console/Application.php(56): _HumbugBox113887eee2b6\Symfony\Component\Console\Application->getDefaultHelperSet()
#5 phar:///Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/bin/box/vendor/symfony/console/Application.php(204): _HumbugBox113887eee2b6\KevinGH\Box\Console\Application->getDefaultHelperSet()
#6 phar:///Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/bin/box/vendor/symfony/console/Command/Command.php(55): _HumbugBox113887eee2b6\Symfony\Component\Console\Application->getHelperSet()
#7 phar:///Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/bin/box/vendor/symfony/console/Application.php(283): _HumbugBox113887eee2b6\Symfony\Component\Console\Command\Command->setApplication(Object(_HumbugBox113887eee2b6\KevinGH\Box\Console\Application))
#8 phar:///Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/bin/box/vendor/symfony/console/Application.php(787): _HumbugBox113887eee2b6\Symfony\Component\Console\Application->add(Object(_HumbugBox113887eee2b6\Symfony\Component\Console\Command\HelpCommand))
#9 phar:///Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/bin/box/vendor/symfony/console/Application.php(362): _HumbugBox113887eee2b6\Symfony\Component\Console\Application->init()
#10 phar:///Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/bin/box/vendor/symfony/console/Application.php(163): _HumbugBox113887eee2b6\Symfony\Component\Console\Application->find('compile')
#11 phar:///Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/bin/box/vendor/symfony/console/Application.php(101): _HumbugBox113887eee2b6\Symfony\Component\Console\Application->doRun(Object(_HumbugBox113887eee2b6\Symfony\Component\Console\Input\ArgvInput), Object(_HumbugBox113887eee2b6\Symfony\Component\Console\Output\ConsoleOutput))
#12 phar:///Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/bin/box/bin/box(41): _HumbugBox113887eee2b6\Symfony\Component\Console\Application->run()
#13 /Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/bin/box(18): require('phar:///Users/l...')
#14 {main} in phar:///Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/bin/box/vendor/symfony/console/Helper/HelperSet.php on line 7
   2. Compile into a single file: ✔


   ErrorException

  rename(/Users/loranger/Developer/projects/nas-cli/nas.phar,/Users/loranger/Developer/projects/nas-cli/builds/nas): No such file or directory

  at vendor/illuminate/filesystem/Filesystem.php:305
    301▕      * @return bool
    302▕      */
    303▕     public function move($path, $target)
    304▕     {
  ➜ 305▕         return rename($path, $target);
    306▕     }
    307▕
    308▕     /**
    309▕      * Copy a file to a new location.

  1   vendor/illuminate/filesystem/Filesystem.php:305
      rename("/Users/loranger/Developer/projects/nas-cli/nas.phar", "/Users/loranger/Developer/projects/nas-cli/builds/nas")

  2   vendor/illuminate/support/Facades/Facade.php:261
      Illuminate\Filesystem\Filesystem::move("/Users/loranger/Developer/projects/nas-cli/nas.phar", "/Users/loranger/Developer/projects/nas-cli/builds/nas")

  3   vendor/laravel-zero/framework/src/Commands/BuildCommand.php:143
      Illuminate\Support\Facades\Facade::__callStatic("move")

  4   vendor/laravel-zero/framework/src/Commands/BuildCommand.php:93
      LaravelZero\Framework\Commands\BuildCommand::compile("nas")

  5   vendor/laravel-zero/framework/src/Commands/BuildCommand.php:71
      LaravelZero\Framework\Commands\BuildCommand::build("nas")

  6   vendor/illuminate/container/BoundMethod.php:36
      LaravelZero\Framework\Commands\BuildCommand::handle()

  7   vendor/illuminate/container/Util.php:40
      Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()

  8   vendor/illuminate/container/BoundMethod.php:93
      Illuminate\Container\Util::unwrapIfClosure(Object(Closure))

  9   vendor/illuminate/container/BoundMethod.php:37
      Illuminate\Container\BoundMethod::callBoundMethod(Object(LaravelZero\Framework\Application), Object(Closure))

  10  vendor/illuminate/container/Container.php:653
      Illuminate\Container\BoundMethod::call(Object(LaravelZero\Framework\Application), [])

  11  vendor/illuminate/console/Command.php:136
      Illuminate\Container\Container::call()

  12  vendor/symfony/console/Command/Command.php:298
      Illuminate\Console\Command::execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))

  13  vendor/illuminate/console/Command.php:121
      Symfony\Component\Console\Command\Command::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))

  14  vendor/laravel-zero/framework/src/Commands/BuildCommand.php:79
      Illuminate\Console\Command::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

  15  vendor/symfony/console/Application.php:1005
      LaravelZero\Framework\Commands\BuildCommand::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

  16  vendor/symfony/console/Application.php:299
      Symfony\Component\Console\Application::doRunCommand(Object(LaravelZero\Framework\Commands\BuildCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

  17  vendor/symfony/console/Application.php:171
      Symfony\Component\Console\Application::doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

  18  vendor/illuminate/console/Application.php:94
      Symfony\Component\Console\Application::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

  19  vendor/laravel-zero/foundation/src/Illuminate/Foundation/Console/Kernel.php:129
      Illuminate\Console\Application::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

  20  vendor/laravel-zero/framework/src/Kernel.php:91
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

  21  nas:37
      LaravelZero\Framework\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

```

</details>

**Comment by owenvoke** [comment]
Yep, this is a known issue. We can't do anything until Box supports PHP 8.1 (https://github.com/box-project/box/issues/562). I think the required changes are already present in the `master` branch, but no tag is ready as work is required for [PHP-Scoper](https://github.com/humbug/php-scoper/issues/530).

I personally don't have enough experience with the code for Box or PHP-Scoper, so I have been waiting for a release to be done.

**Comment by defunctl** [comment]
Box should be supporting [PHP 8.1](https://github.com/box-project/box/releases/tag/3.15.0) now, can we get the box binary updated, please?

**Comment by owenvoke** [comment]
It has been updated for the Laravel Zero 9.x release, @nunomaduro, do you want me to also update the `8.x` branch to use Box 3.15? 👍🏻

**Comment by defunctl** [comment]
That would be amazing @owenvoke if you don't mind!

**Comment by philipnewcomer** [comment]
If it's not too difficult, I would also appreciate having PHP 8.1 support in the 8.x branch, unless the 9.x branch is currently stable enough for production use, or will be released soon.

**Comment by defunctl** [comment]
It does look like box version 3.15.0 [removed PHP 7.3 support](https://github.com/box-project/box/pull/595), which the 8.0 branch still supports...hrmm.

**Comment by defunctl** [comment]
Totally understandable! Thanks for all of your hard work on this excellent project.

@owenvoke Is anything specific done to the `box` phar/binary that's added to the framework, or just bringing in the raw phar from the [box releases](https://github.com/box-project/box/releases) page?

I might just bring in an updated binary for now and make CLI tool's minimum PHP version 7.4 for a bit.

**Comment by nunomaduro** [comment]
@owenvoke You can put both binaries, and use the legacy one if the user is using PHP 7.3.

**Comment by owenvoke** [comment]
@defunctl, yes. It's basically just adding the raw Box Phar binary into `vendor/laravel-zero/framework/bin/box` 👍🏻

@nunomaduro, ok. I think the downside is that the binary gets included in built releases as it's part of the LZ framework afaik. Then it'd end up with 2 binaries which would make the resulting Phar pretty massive. Wonder if we can exclude that directory from the Box output.

**Comment by nunomaduro** [comment]
You can exclude both from the build, updating the box.json on the "build" command.

**Comment by owenvoke** [comment]
If anyone wants to test out the PR that's open for this, feel free to test and add any feedback. 👍🏻
https://github.com/laravel-zero/framework/pull/459

I've stopped using Laravel Zero 8 as all my projects were updatable, so won't really be able to support LZ8 going forward.

**Comment by defunctl** [comment]
Thanks Owen, I'll give it a test today

**Comment by owenvoke** [comment]
This has been merged and tagged as a new Laravel Zero 8 release, please open a new issue if anyone has any issues with building on PHP 8.1 👍🏻 Please also try running with `-vvv` if you do experience issues to make sure that it's not a local issue (e.g. missing extensions).

**Comment by defunctl** [comment]
Build and usage working great here.
