### ISSUE TITLE
VirtualBox filesystem bug causing exceptions

### ISSUE THREAD

**Issue by bilogic** [laravel-zero/laravel-zero#385]
Hi,

I believe I'm running into this issue again (https://github.com/composer/composer/issues/9627), this time with laravel-zero. Basically, there seems to be a race condition in the VirtualBox file system.

To be clear, this is not a bug with `Laravel-zero`, however, adding the code to handle this issue will be greatly appreciated. Hope a PR for this will be accepted.

Below is the output I'm getting when facing the issue
```

                Building process


 Build version? [1.0.0]:
 >

   1. Moving application to production mode: ✔
   2. Compile into a single file: ✔


   ErrorException

  rename(/example/example.phar,/example/builds/example): No such file or directory

  at vendor/illuminate/filesystem/Filesystem.php:307
    303▕      * @return bool
    304▕      */
    305▕     public function move($path, $target)
    306▕     {
  ➜ 307▕         return rename($path, $target);
    308▕     }
    309▕
    310▕     /**
    311▕      * Copy a file to a new location.

      +20 vendor frames
  21  example:37
      LaravelZero\Framework\Kernel::handle()
```

**Comment by bilogic** [comment]
After some debugger, I don't think this is related to the filesystem issue.

I did a `example build -v` and got the following output... Any idea why?

```
? Dumping the Composer autoloader

    > '/usr/local/bin/composer' 'dump-autoload' '--classmap-authoritative' '--no-dev'

PHP Fatal error:  Uncaught Error: Call to undefined function get_debug_type() in phar:///media/sf_www/stage/example/vendor/laravel-zero/framework/bin/box/vendor/symfony/console/Application.php:528
Stack trace:
#0 phar:///media/sf_www/stage/example/vendor/laravel-zero/framework/bin/box/vendor/symfony/console/Application.php(521): _HumbugBox113887eee2b6\Symfony\Component\Console\Application->doActuallyRenderThrowable()
#1 phar:///media/sf_www/stage/example/vendor/laravel-zero/framework/bin/box/vendor/symfony/console/Application.php(496): _HumbugBox113887eee2b6\Symfony\Component\Console\Application->doRenderThrowable()
#2 phar:///media/sf_www/stage/example/vendor/laravel-zero/framework/bin/box/vendor/symfony/console/Application.php(86): _HumbugBox113887eee2b6\Symfony\Component\Console\Application->renderThrowable()
#3 phar:///media/sf_www/stage/example/vendor/laravel-zero/framework/bin/box/vendor/symfony/console/Application.php(106): _HumbugBox113887eee2b6\Symfony\Component\Console\Application->_HumbugBox113887eee2b6\Symfony\Component\Console\{ in phar:///media/sf_www/stage/example/vendor/laravel-zero/framework/bin/box/vendor/symfony/console/Application.php on line 528
```
