### ISSUE TITLE
Phar binary cannot find Application when building app for standalone

### ISSUE THREAD

**Issue by dib258** [laravel-zero/laravel-zero#400]
Hello,

Following [the documentation regarding the build of a standalone app](https://laravel-zero.com/docs/build-a-standalone-application#distribute-via-packagist), I found myself having a bug already described here https://github.com/laravel-zero/laravel-zero/issues/307 on this repository.

The phar was working fine until I moved the `laravel-zero/framework` to `require-dev` 

Here's my `box.json` which came with the  `"exclude-composer-files": false,` configuration out-of-the-box.
```
{
    "chmod": "0755",
    "directories": [
        "app",
        "bootstrap",
        "config",
        "templates",
        "vendor"
    ],
    "files": [
        "composer.json"
    ],
    "exclude-composer-files": false,
    "compression": "GZ",
    "compactors": [
        "KevinGH\\Box\\Compactor\\Php",
        "KevinGH\\Box\\Compactor\\Json"
    ]
}
```

I have : 
- php 8.1.4 
- laravel-zero/foundation : v9.5.1
- laravel-zero/framework : v9.1.1

Here's the error if it helps in any way :
```
PHP Fatal error:  Uncaught Error: Class "LaravelZero\Framework\Application" not found in phar:///[path-to-project]/builds/[app-name]/bootstrap/app.php:14
Stack trace:
#0 phar:///[path-to-project]/builds/[app-name]/[app-name](19): require_once()
#1 /[path-to-project]/builds/[app-name](14): require('phar:///Users/d...')
#2 {main}
  thrown in phar:///[path-to-project]/builds/[app-name]/bootstrap/app.php on line 14

Fatal error: Uncaught Error: Class "LaravelZero\Framework\Application" not found in phar:///[path-to-project]/builds/[app-name]/bootstrap/app.php:14
Stack trace:
#0 phar:///[path-to-project]/builds/[app-name]/[app-name](19): require_once()
#1 /[path-to-project]/builds/[app-name](14): require('phar:///Users/d...')
#2 {main}
  thrown in phar:///[path-to-project]/builds/[app-name]/bootstrap/app.php on line 14
PHP Fatal error:  Uncaught Error: Call to undefined function app() in phar:///[path-to-project]/builds/[app-name]/vendor/spatie/ray/src/helpers.php:23
Stack trace:
#0 phar:///[path-to-project]/builds/[app-name]/vendor/spatie/ray/src/helpers.php(55): ray()
#1 [internal function]: {closure}()
#2 {main}
  thrown in phar:///[path-to-project]/builds/[app-name]/vendor/spatie/ray/src/helpers.php on line 23

Fatal error: Uncaught Error: Call to undefined function app() in phar:///[path-to-project]/builds/[app-name]/vendor/spatie/ray/src/helpers.php:23
Stack trace:
#0 phar:///[path-to-project]/builds/[app-name]/vendor/spatie/ray/src/helpers.php(55): ray()
#1 [internal function]: {closure}()
#2 {main}
  thrown in phar:///[path-to-project]/builds/[app-name]/vendor/spatie/ray/src/helpers.php on line 23
```

Please tell me if I can give more data to help, or if you could point me somewhere to try to help debug. At least the previous fix doesn't seems to work anymore.

Thanks ;)

**Comment by owenvoke** [comment]
You'll need to add `"exclude-dev-files": false,` to your Box configuration as well as `exclude-composer-files`. 👍🏻

**Comment by dib258** [comment]
Wow didn't see no difference, I read this file at least 10 times! Thank you for you quick answer @owenvoke 
The fix still works!
